# Generated by Django 5.2 on 2025-04-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='current_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('checkings', 'Checkings/Giro'), ('savings', 'Savings'), ('credit_card', 'Credit Card')], max_length=20),
        ),
    ]
